version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    dir: ./cmd/grimoire
    binary: grimoire
brews:
  - name: grimoire
    repository:
      owner: datadog
      name: grimoire
      branch: "homebrew-update-{{ .Version	}}"
      pull_request:
        enabled: true
        base:
          owner: datadog
          name: grimoire
          branch: main
    directory: Formula
    url_template: "https://github.com/DataDog/grimoire/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license: Apache-2.0
    homepage: "https://github.com/DataDog/grimoire"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
