# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grimoire < Formula
  desc ""
  homepage "https://github.com/DataDog/grimoire"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/DataDog/grimoire/releases/download/v0.0.1/grimoire_Darwin_x86_64.tar.gz"
      sha256 "5d2794d6bffffa7dd51b272957cee854e483915c9784b087691b020efacfd4ab"

      def install
        bin.install "grimoire"
      end
    end
    on_arm do
      url "https://github.com/DataDog/grimoire/releases/download/v0.0.1/grimoire_Darwin_arm64.tar.gz"
      sha256 "f6f695a58d12698a3a325a278d5c79897f6571c8bc785abe2965ffce3b306ed0"

      def install
        bin.install "grimoire"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DataDog/grimoire/releases/download/v0.0.1/grimoire_Linux_x86_64.tar.gz"
        sha256 "1c88560b3feeb9ebd1052fc953bcc303ba9ff8779c0c3ce9311f69248d52cabc"

        def install
          bin.install "grimoire"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DataDog/grimoire/releases/download/v0.0.1/grimoire_Linux_arm64.tar.gz"
        sha256 "6fe91c3f5fcffbc643436247dcb661cdca33bf99a1475402db2c1dd6d2cee5b3"

        def install
          bin.install "grimoire"
        end
      end
    end
  end
end
